### PR TITLE
changed install composer and syntax highlighting

### PR DESCRIPTION
**Pull request by royopa**

### CODE REVIEW

**Comment by DannyBen** [comment]
Thanks. 

1. I am not using composer myself - why the change to `composer require dannyben/php-quandl` ?
2. The syntax changes at the bottom part, the extra backticks are viewed in the result, need to remove. [example](https://github.com/DannyBen/php-quandl/pull/3/files#diff-04c6e90faac2675aa89e2176d2eec7d8R136)

**Comment by royopa** [comment]
Hi @DannyBen I added the two forms to install, please see in my PR. [In this link](http://blog.doh.ms/2014/10/13/installing-composer-packages/) have a good article from @rdohms to use Composer. 
Particularly I prefer to use composer require, because my composer.json is updated automatically.
Regards!

**Comment by DannyBen** [comment]
Thanks @royopa

**Comment by rdohms** [comment]
You should drop the "manually edit composer.json" completely for a couple reasons:

1) Using `*` has performance and sanity problems
2) You do not mention following steps like install or update
3) Because of those `require` is recommended as its automatic and atomic 

For these reasons I would drop that completely and just leave the `require`, you may notice that its also what the new packagist suggest as install command.

**Comment by DannyBen** [comment]
@rdohms , 

> You should drop the "manually edit composer.json" completely for a couple reasons:

From the [packagist website](https://packagist.org/): "Put a file named composer.json at the root of your project, containing your project dependencies:". This is also the same pattern I saw on [other PHP projects](https://github.com/smarty-php/smarty). Please share a reference to an official page that provides a better set of instructions, and I will gladly change.

> 1) Using * has performance and sanity problems

This is an example composer file, not a lesson in using composer or managing dependencies. If you know what you want, put any version spec you want. I see no reason to create a situation where I need to update the readme with each release.

> 2) You do not mention following steps like install or update

Not sure I am following. Do you mean you expect to see all the composer commands here? This is not a composer tutorial, so if this is your meaning, I disagree. If something else, please elaborate.

**Comment by rdohms** [comment]
> From the packagist website: "Put a file named composer.json at the root of your project, containing your project dependencies:". This is also the same pattern I saw on other PHP projects. Please share a reference to an official page that provides a better set of instructions, and I will gladly change.

Don't confuse "getting started" with "installing new dependencies". If you look at any packages page on packagist, you will see this:

screen shot 2015-06-17 at 10 30 47

But if you want to use other packages as a pattern, this search may be interesting: https://github.com/search?utf8=%E2%9C%93&q=%27composer+require%27+extension%3Amd&type=Code&ref=advsearch&l=

> This is an example composer file, not a lesson in using composer or managing dependencies. If you know what you want, put any version spec you want. I see no reason to create a situation where I need to update the readme with each release.

If you use the command `composer require <yourpackage> ` you do not need to change it since it does not mention any version, as composer will sort out and install the latest version compatible with your setup, making it a lot less error prone. 

However by using the example with `*` what happens is most users will simply copy as paste that example and end up using the `*` for simple lack of knowledge or research, hence leading to more version problems in the ecosystem.

With this i recommend this since its the lowest "maintenance" way of telling people to install your library.

> Not sure I am following. Do you mean you expect to see all the composer commands here? This is not a composer tutorial, so if this is your meaning, I disagree. If something else, please elaborate.

Simply adding stuff to composer.json does not install libraries, so they need to either run install after or update. This by itself makes the install instructions lacking. However very few people know about limited install/update so what happens is that to install one new library they run a regular composer update, which brings in new versions and may give them other side effects to deal with, that leads to blaming your library usually.

The `require` command does all of this atomically with as little side effects as possible, its one command not a list, so its by far more user friendly then editing the composer file manually.

Again, you don't have to do anything, i'm just giving you input from the results of the research i did in order to write a talk and book on the subject, so I thought i would give you some tips. Feel free to disagree and leave as is.

**Comment by DannyBen** [comment]
@rdohms - thanks, this is an excellent description of the situation and I am convinced.

See the [README.md on the dev branch](https://github.com/DannyBen/php-quandl/blob/dev/README.md) - does this look as expected?

**Comment by rdohms** [comment]
yep, that looks pretty good, glad i could help.

**Comment by DannyBen** [comment]
Great. Appreciate your help, will merge to master soon.

**Pull request merged**
